### ISSUE TITLE
Include mermaid 8.14 in the asset?

### ISSUE THREAD

**Issue by mbergkvist** [badboy/mdbook-mermaid#16]
The mermaid.js included with mdbook-mermaid is 8.9. mermaid.js is now on 8.14, any chances the included asset will be upgraded anytime soon?

**Comment by badboy** [comment]
There's no 8.14.0 on https://github.com/mermaid-js/mermaid/releases/
I can upgrade to 8.13 though

**Comment by mbergkvist** [comment]
> There's no 8.14.0 on https://github.com/mermaid-js/mermaid/releases/

My mistake. I was looking at https://github.com/mermaid-js/mermaid/packages/46638

Thanks for the swift response and the work with this package!
