### ISSUE TITLE
Simple example from readme has an extra backtick box 

### ISSUE THREAD

**Issue by deepankarsharma** [badboy/mdbook-mermaid#20]
Using the following markup results in the image below

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

![Extra superfluous backtick box](https://user-images.githubusercontent.com/840385/175211912-0c92cde7-71f7-4292-bc5d-770cd378b775.png)

This is on mdbook-mermaid v0.11.0

**Comment by deepankarsharma** [comment]
Never mind, issue was on my side. mdbook was having some issues with my markup and running mdbook test revealed what the issue was.

**Comment by ChrisB9** [comment]
I do have the same issue, in the markdown rendering there are 4 backticks everywhere. How did you solve your problem?

**Comment by drahnr** [comment]
Had a similar issue, with the ` `` showing up and subsequent graphz not rendering in the mdbook, I had `graphviz` as plugin and `linkcheck` as output check. Removed both, and the issues went away.
