### ISSUE TITLE
Error: Command:mdbook-mermaid

### ISSUE THREAD

**Issue by elgirafo** [badboy/mdbook-mermaid#22]
I followed all the installation steps however, it seems like mdbook is not recognizing the mdbook-mermaid command to render the mermaid code when serving it on localhost. 

Here is a screenshot, any chance it requires a specific update?
![Screenshot 2022-07-27 at 15 41 18](https://user-images.githubusercontent.com/80516439/181310723-cf4926b8-d653-47c1-8990-faa983ff33d8.jpg)

**Comment by elgirafo** [comment]
I changed the syntax following the plantuml plug-in but I get a mermaid version error. 
![Screenshot 2022-07-27 at 18 56 16](https://user-images.githubusercontent.com/80516439/181340372-42d9de78-7d17-4cb9-964c-47cbcab973e3.jpg)

**Comment by badboy** [comment]
mdbook-mermaid bundles mermaid.js 9.1.1, which includes a fix for https://github.com/mermaid-js/mermaid/issues/3025, as can also seen in that error display.
It also says "Syntax error in graph", so maybe you mistyped something in the mermaid code block?

`mermaid-cmd` is not something `mdbook` recognizes. This just means the `command` is unset, so it will default to `mdbook-mermaid` (as per [the docs](https://rust-lang.github.io/mdBook/format/configuration/preprocessors.html#custom-preprocessor-configuration)).
Maybe `mdbook-mermaid` was simply not correctly in your path? Or you have some typo or invisible character in that first config.

Anyway, this all doesn't sound like an issue with this crate really, but please do re-open the bug with more info if you have some.

**Comment by nickspurry** [comment]
This issue had me pulling my hair out for a little while, so I'll leave this here just in case anyone else experiences it as well. I had the same problem as the first issue in this bug report. Following the installation instructions exactly as in README, I got:
```
mdbook serve --open
[INFO] (mdbook::book): Book building has started
[WARN] (mdbook::preprocess::cmd): The command wasn't found, is the "mermaid" preprocessor installed?
[WARN] (mdbook::preprocess::cmd):   Command: mdbook-mermaid
```
`mdbook` doesn't find the `mdbook-mermaid` preprocessor in `PATH`, even though I could run `mdbook-mermaid` directly in the terminal, implying that there are no issues with `PATH`.

In my case, `mdbook-mermaid` is included in `PATH` through the relative path `~/.cargo/bin`. This relative path seems to be problematic for `mdbook`. Using an absolute path the cargo binaries fixed the issue:
```
export PATH=$PATH:/absolute/path/to/.cargo/bin
```
It's unclear why `mdbook` can't properly find binaries in `PATH`. This issue might be related to `mdbook` [issue 2040](https://github.com/rust-lang/mdBook/issues/2040).
