### ISSUE TITLE
mermaid block code not rendered

### ISSUE THREAD

**Issue by frafra** [badboy/mdbook-mermaid#25]
```
Could not find the language 'mermaid', did you forget to load/include a language module? [highlight.js:6:14150](https://ninanor.github.io/91126800_ML_and_associated_tech/highlight.js)
Falling back to no-highlight mode for this block. 
<code class="language-mermaid">
```

This is how I fixed it: `mermaid.init({startOnLoad:true}, document.querySelectorAll(".language-mermaid"));`

I am not sure if something changed in the latest version of mdbook.

**Comment by badboy** [comment]
I'm not able to reproduce this issue in my local test instance.
Can you point me to the source code of the failing book to try it out?
