### ISSUE TITLE
Markdown files with CR LF line endings instead of LF do not create mermaid output

### ISSUE THREAD

**Issue by pseiko1989** [badboy/mdbook-mermaid#26]
Markdown files with CR-LF line endings will only create an empty
```html
<pre class="mermaid">
</pre>
```
instead of the code block.

It should be possible to verify it with the following files:
[test_cr_lf.md](https://github.com/badboy/mdbook-mermaid/files/10093495/test_cr_lf.md)
[test_lf.md](https://github.com/badboy/mdbook-mermaid/files/10093496/test_lf.md)

The cause of this may be that events.into_offset_iter() in https://github.com/badboy/mdbook-mermaid/blob/main/src/lib.rs#L64
returns the mermaid content line by line instead of in one big chunk.

**Comment by badboy** [comment]
PRs welcome. I don't have CRLF line endings, so I'm not too eager to investigate this right now.
