### ISSUE TITLE
how can I upgrade to latest mermaid version 9.2.2 correctly?

### ISSUE THREAD

**Issue by jay-zhou-yan** [badboy/mdbook-mermaid#28]
Hi

Thank you very much for this excellent preprocessor !  Thanks again.

Here, I encountered a problem. I wanted to use the Mindmaps function of mermaid. I referred to the issue solution of #18  & #19 , replaced the 9.2.2 version of assert/mermaid.min.js, recompiled mdbook mermaid, and cooperated with mdbook. However, when I encountered Mindmaps, I would still prompt "**Syntax error in graph mermaid version 9.2.2**". Could you give me some advice on how to upgrade?  Thanks.

**Comment by badboy** [comment]
I might get around to updating it in repo this week.

Where's that error logged? Can you give a book example I can use to test?

**Comment by badboy** [comment]
the mindmaps functionality is in an external plugin: https://mermaid-js.github.io/mermaid/#/mindmap?id=integrating-with-your-librarywebsite

You will need to download that ([url](https://unpkg.com/@mermaid-js/mermaid-mindmap@9/dist/mermaid-mindmap.min.js)), add it to the `additional-js` list in your `book.toml`, then change your `mermaid-init.js` to:

```javascript
mermaid.registerExternalDiagrams([window["mermaid-mindmap"]]).then(() => mermaid.initialize({startOnLoad:true}));
```

**Comment by jay-zhou-yan** [comment]
Thank you very much for your guide.  Now using mdbook-mermaid with mdbook can handle mindmap correctly. 

I was made of the markdown files in the 

> https://github.com/mermaid-js/mermaid/tree/develop/docs

 for test (of course I have modified the inside part of the grammar errors before testing).
