### ISSUE TITLE
mermaid V10 support

### ISSUE THREAD

**Issue by suda-morris** [badboy/mdbook-mermaid#32]
According to https://github.com/mermaid-js/mermaid/releases/tag/v10.0.0 mermaid has dropped the CJS support.

**Comment by kirill-d-lappo** [comment]
as a temporary workaround after `mdbook-mermaid init` 

* download the latest version from mermaid site/cdn
* update `mermaid.min.js` in the base folder near `book.toml`
* flush `./book/` folder 
* rebuild the book

**Comment by friegger** [comment]
Any update on this? Would it be an option to also allow downloading the latest or a specific version of mermaid when executing `mdbook-mermaid install`. Then it would not be necessary to touch mdbook-mermaid every time a new mermaid release is available.

**Comment by badboy** [comment]
`mdbook-mermaid install` is a convenience command to drop the required files into your folder. If you need a different, more recent version you can do that by downloadig it manually and putting the files in the right place.

I won't add more complex code for arbitrary downloads.
I didn't have time to update to v10 yet and currently it's not a priority for me.

**Comment by char101** [comment]
It's easy to add mermaid-js v10 manually

1. Remove `additional-js = ["mermaid.min.js", "mermaid-init.js"]` from `book.toml`
2. Create `theme/header.hbs` containing
```html
<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
  mermaid.initialize({ startOnLoad: true });
</script>
```

**Comment by yatesco** [comment]
`theme/head.hbs` is relative to the project root (so `theme` is a sibling of `src`). This is just a note for those like me who stupidly added it to the transient 'book' directory and wondered why it kept disappearing ;-)

Works really well - thanks @char101

**Comment by tetsushiawano** [comment]
for me, this solution works on github pages, but when do print, it can not use the V10.

**Comment by NTmatter** [comment]
From a quick bit of playing, it seems like we can overwrite the local copy of mermaid. It gets picked up and used buy the build:
```shell
curl -LO https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
```

Beware of local browser cache!
