### ISSUE TITLE
Diagrams not being rendered

### ISSUE THREAD

**Issue by SergioGasquez** [badboy/mdbook-mermaid#34]
Hi! I'm a maintainer of https://github.com/esp-rs/book where we are using `mdbook-mermaid`. We've followed the instructions and the diagrams have been working fine for a year or so, but a few months ago they[ stopped working](https://esp-rs.github.io/book/overview/using-the-standard-library.html#relevant-esp-rs-crates), see https://github.com/esp-rs/book/issues/102. We tried updating the `*.js` files generated by mermaid to the latest, see https://github.com/esp-rs/book/pull/90, but the issue still persists.

**Comment by badboy** [comment]
Works locally for me.

Your CI warns that `mdbook-mermaid` is not actually installed (see below.
Probably your cache does not have it, but you skip installing it. I also don't see where/how you install `mdbook`, so I don't know which version you use. Make sure to use an up-to-date version.

Output from https://github.com/esp-rs/book/actions/runs/5244960850/jobs/9492395891

```
2023-06-13 10:15:35 [INFO] (mdbook::book): Book building has started
2023-06-13 10:15:35 [WARN] (mdbook::preprocess::cmd): The command wasn't found, is the "mermaid" preprocessor installed?
2023-06-13 10:15:35 [WARN] (mdbook::preprocess::cmd): 	Command: mdbook-mermaid
2023-06-13 10:15:35 [INFO] (mdbook::book): Running the html backend
```

**Comment by SergioGasquez** [comment]
> Works locally for me.

Yes, forgot to mention that it was also working locally for me. 

Thanks for pointing at the CI warning, it was indeed, a cache thing, I wish that that warning was an error.

Thanks a lot for your quick help!
