### ISSUE TITLE
Mdbook Mermaid dark mode support

### ISSUE THREAD

**Issue by hemeroc** [badboy/mdbook-mermaid#35]
**Expectation:**
When switching to a dark theme in mdbook the mermaid diagrams also switch to a dark theme.
<img width="570" alt="image" src="https://github.com/badboy/mdbook-mermaid/assets/193428/c412f795-0c5a-49aa-a79b-6037ed793037">

**What happens:**
Mermaid diagrams do not honor the theme and render in light mode being not very readable in dark mode.
<img width="470" alt="image" src="https://github.com/badboy/mdbook-mermaid/assets/193428/7fd70227-92d5-43c9-a816-d00bb2c8d35d">

I am happy to help if you point me to the right start.

**Comment by hemeroc** [comment]
I think mdbook-mermaid would need to implement a switching that at least provides a default mapping from the default mdbook themes to the light or dark mermaid themes.

I would see mdbook-mermaid as a mermaid bridge for mdbook that should integrate mermaid diagrams into mdbook and not produce diagrams that you can't read in one of the default themes.

I would be absolutely willing to implement this if you could hint me in the right direction.

**Comment by badboy** [comment]
mdbook-mermaid currently doesn't handle any theming on its own at all.
mdbook handles theming by applying a class to the `<html>` event.

You might need to either:

* Write some JS to watch for that change and apply some mermaid theming
* Extend the CSS of the theme to apply to mermaid styling as well

Both things can be tried out in your own project by modifying the additional JS or CSS files.
If that leads to a more general solution we might be able to bring this back into this plugin.
