### ISSUE TITLE
Pre-render the graphs

### ISSUE THREAD

**Issue by roberth** [badboy/mdbook-mermaid#36]
It would be nice to have mdbook-mermaid invoke the renderer ahead of time. Some benefits
 - Syntax errors can be caught early; during the site build process.
 - Probably faster as inline SVGs are probably cheaper. Loading time comes mostly from having many files, and this way we can remove the two scripts.
 - No complaints from readers who have disabled javascript.

I don't know if the mermaid does anything useful that's browser dependent, or whether that'd be important. If it is, the js could still be loaded I presume, but I really don't expect that to be needed.

**Comment by badboy** [comment]
You can use the [mermaid cli](https://github.com/mermaid-js/mermaid-cli) to generate svgs or pngs.
But I have currently no intention to build it into this tool.
If you want though take the code, replace [this part](https://github.com/badboy/mdbook-mermaid/blob/main/src/lib.rs#L92-L104) with an invocation of the CLI and insert a new image tag (and figure out where to put the image).

**Comment by roberth** [comment]
That's [this part](https://github.com/badboy/mdbook-mermaid/blob/8fab86e0008762193b2032a7c7a34956c26c7432/src/lib.rs#L92-L104) as a permalink for future reference.
