### ISSUE TITLE
Implement dark mode support for mermaid.

### ISSUE THREAD

**Issue by AnthonyTornetta** [badboy/mdbook-mermaid#38]
Supporting dark theme on mermaid is a relatively easy fix that should be supported out of the box. All the changes required would be in mermaid-init.js, and could be changed by the end user if required.

It would be as simple as reading the class appended to the HTML field and choosing mermaid's theme accordingly before initializing it.

**Comment by xyzst** [comment]
@badboy : do you see any issues here? Seems like @AnthonyTornetta has addressed concerns expressed here: https://github.com/badboy/mdbook-mermaid/issues/35#issuecomment-1614564202

**Comment by badboy** [comment]
I don't know. I won't have time to look into this, maybe after the holidays.
