### ISSUE TITLE
Making use of CDN

### ISSUE THREAD

**Issue by steinemann** [badboy/mdbook-mermaid#41]
Hi,

I am struggling with using this plugin currently because, I don't like to put the ~3MB large `mermaid.min.js` into my repo, as discribed 
in the installation instructions.

Is there a way to make use of the CDN network and just use the corresponding `mermaid.min.js` file from there on client side ? 
> E.g. https://www.jsdelivr.com/package/npm/mermaid

Thanks,
Peter

**Comment by louwers** [comment]
This should be the recommended approach. It is insecure to just have a blob of code in a repo.

**Comment by louwers** [comment]
>     0: Unable to copy across additional CSS and JS
>  1: Unable to copy /Users/bart/src/maplibre-native/docs/mdbook/https://cdn.jsdelivr.net/npm/mermaid@11.6.0/dist/mermaid.min.js to /Users/bart/src/maplibre-native/docs/mdbook/book/https://cdn.jsdelivr.net/npm/mermaid@11.6.0/dist/mermaid.min.js

**Comment by badboy** [comment]
> This should be the recommended approach. It is insecure to just have a blob of code in a repo.

uuuh what? no.



> > ```
> > 0: Unable to copy across additional CSS and JS
> > ```

Ah well, guess `mdbook` indeed wants to copy `additional-js` files.
In that case you will have to modify your template to directly link to the URLs instead of local files.

But again: not something this plugin will do for you.
