### ISSUE TITLE
Mermaid update via dependabot

### ISSUE THREAD

**Issue by antoniovazquezblanco** [badboy/mdbook-mermaid#43]
It seems that mermaid is quite often updated and newer versions include amazing new functionalities that I would like to use. I guess that manually checking for newer versions of the lib is not feasible nor desirable.

It would be awesome to create an npm project in this repo that contains both mermaid and the initialization code and that generates a resulting js file that is then packed as an asset in the cargo project.
In this way, one may be able to automate dependency tracking and updating via dependabot that would do that for us!

Would you be open to this idea?
Do you have any recommendations on structure and how to organize this code to not mix the cargo and npm code?

Thank you!

**Comment by badboy** [comment]
No, I'm not gonna maintain an npm package.
But in your own project you can just re-deploy a new mermaid.js, there's no need for this wrapper to contain the new version.

**Comment by antoniovazquezblanco** [comment]
I totally understand this. I will update mermaid.js locally.
Thank you for the the awesome project.
