### ISSUE TITLE
Using ELK layout with mermaid v11

### ISSUE THREAD

**Issue by isma-xnm** [badboy/mdbook-mermaid#49]
It seems like `layout: "elk"` does not work with the bundled `mermaid.min.js` due to ELK layout not being included by default.
Additionally, it seems like the `@mermaid-js/layout-elk` package only supports ESM (which doesn't work with mdbook's `additional-js` option).
This can be fixed by manually editing the mermaid build script and adding IIFE builds for elk-layout:

```diff
index 2bb42a557..68bbf7528 100644
--- a/.esbuild/build.ts
+++ b/.esbuild/build.ts
@@ -22,7 +22,7 @@ const buildPackage = async (entryName: keyof typeof packageOptions) => {
     { ...commonOptions, core: true },
   ];

-  if (entryName === 'mermaid') {
+  if (entryName === 'mermaid' || entryName === 'mermaid-layout-elk') {
     const iifeOptions: MermaidBuildOptions = { ...commonOptions, format: 'iife' };
     buildConfigs.push(
       // mermaid.js
diff --git a/.esbuild/util.ts b/.esbuild/util.ts
index 522176113..82c24c3a4 100644
--- a/.esbuild/util.ts
+++ b/.esbuild/util.ts
@@ -84,11 +84,12 @@ export const getBuildConfig = (options: MermaidBuildOptions): BuildOptions => {
   if (format === 'iife') {
     output.format = 'iife';
     output.splitting = false;
-    output.globalName = '__esbuild_esm_mermaid';
+    const globalName = name.replace(/-([a-z])/gm, (_, c) => c.toUpperCase());
+    output.globalName = '__esbuild_esm_' + globalName;
     // Workaround for removing the .default access in esbuild IIFE.
     // https://github.com/mermaid-js/mermaid/pull/4109#discussion_r1292317396
     output.footer = {
-      js: 'globalThis.mermaid = globalThis.__esbuild_esm_mermaid.default;',
+      js: `globalThis.${globalName} = globalThis.__esbuild_esm_${globalName}.default;`,
     };
     output.outExtension = { '.js': '.js' };
   } else {
```

...loading the built module in `book.toml`...
```toml
[output.html]
additional-js = ["mermaid.min.js", "mermaid-layout-elk.min.js", "mermaid-init.js"]
```
...and then loading the layouts in `mermaid-init.js`:
```js
    mermaid.registerLayoutLoaders(mermaidLayoutElk);
```

This works, but I'm not sure where (or if) to create PRs. If nothing else, perhaps this helps someone else with the same problem.
Adding the patch and a pre-built js file (if you trust it).

[mermaid-elk-iife.patch](https://github.com/user-attachments/files/17295920/mermaid-elk-iife.patch)
[mermaid-layout-elk.min.js.zip](https://github.com/user-attachments/files/17295921/mermaid-layout-elk.min.js.zip)

**Comment by badboy** [comment]
We default-bundle the minified generated mermaid file directly from unpkg.com.
We don't change it nor do we touch its build system.
It's easy enough for anyone to swap out what they deploy though.
