### ISSUE TITLE
implement dark mode?

### ISSUE THREAD

**Issue by azarmadr** [badboy/mdbook-mermaid#8]
thankful for the library.
also the mermaid version can be updated i guess?

**Comment by mcobzarenco** [comment]
Thanks for the library! Additionally to this issue, is it generally possible to customize the theme?

**Comment by badboy** [comment]
Updated the bundled mermaid just now (release upcoming).
You still need to manually replace your mermaid.min.js (or remove it and run `mdbook-mermaid install` again). 
I also removed the CSS file, theming seems to be handled differently now: https://mermaid-js.github.io/mermaid/#/theming
